### ISSUE TITLE
Not working on Windows Chrome

### ISSUE THREAD

**Issue by miguel-sc** [doebi/liquidfun.js-demo#3]
LiquidfunSprite is not being rendered on Windows Chrome.

**Comment by chrsi** [comment]
Works fine in Version 63.0.3239.132
Please specify your version

![image](https://user-images.githubusercontent.com/1976206/35927282-9eb03b64-0c2a-11e8-93dc-45cb29a49119.png)

**Comment by miguel-sc** [comment]
The latest Version of Chrome 64.0.3282.140 on Windows 10.
I will try it on different machines then, maybe it's some extension that's messing it up.

**Comment by miguel-sc** [comment]
I tested it on other machines. It works perfectly fine. Sorry for the false alarm.
